version: '1.0.{build}'

image: Visual Studio 2017

branches:
  only:
    - master
    
platform:
  - x64

configuration:
  - Release
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  
install:
  - git submodule update --init --recursive
  - cd c:\tools\vcpkg\
  - git fetch https://github.com/TMwhuhan/vcpkg.git 
  - .\bootstrap-vcpkg.bat
  - vcpkg upgrade --no-dry-run
  - vcpkg list
  - vcpkg install
        openimageio[libraw]
        rocksdb
        --triplet %PLATFORM%-windows
        --recurse
  - vcpkg list
before_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - md build
    - cd build
    - cmake .. -G "Visual Studio 14 2015 Win64"
            -DCMAKE_BUILD_TYPE=%CONFIGURATION%
            -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    - ls -l
build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\aliceVision.sln
  verbosity: minimal
  
cache:
  c:\tools\vcpkg\installed\
